### LOCAL Profile
server:
  port: 8081
spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/call_billing?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
#    platform: mysql
#    continue-on-error: true
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto : update
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-persistence.xml

logging.level:
  com.backbase: DEBUG

